server:
  port: 8086

spring:
  application:
    name: presence-service
  config:
    import: "optional:configserver:http://config-server:8888"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
